import { Curriculum } from "./curriculum-type";

export const curriculum: Curriculum = {
  Ponedeljak: [
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "P",
      groups: ["A7", "A8", "A9"],
      time: "08:15 - 10:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Matematika 1",
      type: "P",
      groups: ["A4", "A5", "A6"],
      time: "08:15 - 10:00",
      location: "Amfiteatar 1",
    },
    {
      subject: "Ekonomija",
      type: "P",
      groups: ["A1", "A2", "A3"],
      time: "08:15 - 10:00",
      location: "Amfiteatar 2",
    },
    {
      subject: "Matematika 1",
      type: "P",
      groups: ["A7", "A8", "A9"],
      time: "10:15 - 12:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "P",
      groups: ["A4", "A5", "A6", "A10"],
      time: "10:15 - 12:00",
      location: "Amfiteatar 1",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "P",
      groups: ["A1", "A2", "A3"],
      time: "10:15 - 12:00",
      location: "Amfiteatar 2",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "P",
      groups: ["A11", "A12", "A13"],
      time: "12:15 - 14:00",
      location: "Amfiteatar 1",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A1", "A3"],
      time: "12:15 - 14:00",
      location: "09",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A7"],
      time: "12:15 - 14:00",
      location: "60",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A5"],
      time: "12:15 - 14:00",
      location: "14",
    },
    {
      subject: "Ekonomija",
      type: "P",
      groups: ["A14", "A15", "A16"],
      time: "12:15 - 14:00",
      location: "Amfiteatar 5",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A4"],
      time: "12:15 - 14:00",
      location: "13",
    },
    {
      subject: "Menadžment",
      type: "P",
      groups: ["A10", "A17", "A18"],
      time: "12:15 - 14:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A1", "A3"],
      time: "12:15 - 14:00",
      location: "08",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A7"],
      time: "12:15 - 14:00",
      location: "61",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A1", "A3"],
      time: "12:15 - 14:00",
      location: "20",
    },
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A10"],
      time: "14:15 - 16:00",
      location: "12",
    },
    {
      subject: "Osnovi organizacije",
      type: "P",
      groups: ["A14", "A15", "A16"],
      time: "14:15 - 16:00",
      location: "Amfiteatar 5",
    },
    {
      subject: "Menadžment",
      type: "P",
      groups: ["A11", "A12", "A13"],
      time: "14:15 - 16:00",
      location: "Amfiteatar 1",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A17"],
      time: "14:15 - 16:00",
      location: "13",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A18"],
      time: "14:15 - 16:00",
      location: "16",
    },
    {
      subject: "Osnovi organizacije",
      type: "P",
      groups: [
        "A1",
        "A2",
        "A3",
        "A4",
        "A5",
        "A6",
        "A7",
        "A8",
        "A9",
        "A10",
        "A11",
        "A12",
        "A13 ",
      ],
      time: "16:15 - 18:00",
      location: "Amfiteatar 1",
    },
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A17"],
      time: "16:15 - 18:00",
      location: "13",
    },
  ],
  Utorak: [
    {
      subject: "Menadžment",
      type: "P",
      groups: ["A14", "A15", "A16"],
      time: "08:15 - 10:00",
      location: "Amfiteatar 2",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A8"],
      time: "08:15 - 10:00",
      location: "50",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A8"],
      time: "08:15 - 10:00",
      location: "60",
    },
    {
      subject: "Engleski jezik u informatici",
      type: "P",
      groups: ["A1", "A2", "A3"],
      time: "08:15 - 10:00",
      location: "Amfiteatar 1",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A7"],
      time: "08:15 - 10:00",
      location: "13",
    },
    {
      subject: "Matematika 1",
      type: "P",
      groups: ["A10", "A17", "A18"],
      time: "08:15 - 10:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A13"],
      time: "10:15 - 12:00",
      location: "21",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "P",
      groups: ["A10", "A17", "A18"],
      time: "10:15 - 12:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Ekonomija",
      type: "P",
      groups: ["A7", "A8", "A9"],
      time: "10:15 - 12:00",
      location: "Amfiteatar 4",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A6"],
      time: "10:15 - 12:00",
      location: "13",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A4"],
      time: "10:15 - 12:00",
      location: "50",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "P",
      groups: ["A1", "A2", "A3"],
      time: "10:15 - 12:00",
      location: "Amfiteatar 1",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A4"],
      time: "10:15 - 12:00",
      location: "60",
    },
    {
      subject: "Matematika 1",
      type: "P",
      groups: ["A14", "A15", "A16"],
      time: "10:15 - 12:00",
      location: "Amfiteatar 2",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "P",
      groups: ["A14", "A15", "A16"],
      time: "12:15 - 14:00",
      location: "Amfiteatar 2",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A3"],
      time: "12:15 - 14:00",
      location: "60",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A10", "A17"],
      time: "12:15 - 14:00",
      location: "17",
    },
    {
      subject: "Osnovi organizacije",
      type: "V",
      groups: ["A13"],
      time: "12:15 - 14:00",
      location: "21",
    },
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A11"],
      time: "12:15 - 14:00",
      location: "20",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A10", "A17"],
      time: "12:15 - 14:00",
      location: "09",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A9"],
      time: "12:15 - 14:00",
      location: "13",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A10", "A17"],
      time: "12:15 - 14:00",
      location: "08",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A3"],
      time: "12:15 - 14:00",
      location: "50",
    },
    {
      subject: "Ekonomija",
      type: "P",
      groups: ["A4", "A5", "A6"],
      time: "12:15 - 14:00",
      location: "Amfiteatar 4",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A5"],
      time: "14:15 - 16:00",
      location: "60",
    },
    {
      subject: "Francuski jezik u informatici",
      type: "P",
      groups: ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10"],
      time: "14:15 - 16:00",
      location: "07",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A5"],
      time: "14:15 - 16:00",
      location: "50",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A12", "A13"],
      time: "14:15 - 16:00",
      location: "08",
    },
    {
      subject: "Osnovi organizacije",
      type: "V",
      groups: ["A11"],
      time: "14:15 - 16:00",
      location: "20",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A12", "A13"],
      time: "14:15 - 16:00",
      location: "21",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A12", "A13"],
      time: "14:15 - 16:00",
      location: "09",
    },
    {
      subject: "Francuski jezik u informatici",
      type: "V",
      groups: ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10"],
      time: "16:15 - 18:00",
      location: "07",
    },
    {
      subject: "Osnovi organizacije",
      type: "V",
      groups: ["A12"],
      time: "16:15 - 18:00",
      location: "21",
    },
  ],
  Sreda: [
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A4"],
      time: "08:15 - 10:00",
      location: "30",
    },
    {
      subject: "Ekonomija",
      type: "V",
      groups: ["A7"],
      time: "08:15 - 10:00",
      location: "14",
    },
    {
      subject: "Menadžment",
      type: "P",
      groups: ["A1", "A2", "A3"],
      time: "08:15 - 10:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A8"],
      time: "08:15 - 10:00",
      location: "12",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A15"],
      time: "08:15 - 10:00",
      location: "18",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A11", "A15"],
      time: "10:15 - 12:00",
      location: "21",
    },
    {
      subject: "Menadžment",
      type: "P",
      groups: ["A7", "A8", "A9"],
      time: "10:15 - 12:00",
      location: "Amfiteatar 5",
    },
    {
      subject: "Matematika 1",
      type: "P",
      groups: ["A1", "A2", "A3"],
      time: "10:15 - 12:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A14"],
      time: "10:15 - 12:00",
      location: "14",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A11", "A15"],
      time: "10:15 - 12:00",
      location: "40",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A11", "A15"],
      time: "10:15 - 12:00",
      location: "50",
    },
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A12"],
      time: "10:15 - 12:00",
      location: "30",
    },
    {
      subject: "Ekonomija",
      type: "V",
      groups: ["A4", "A5"],
      time: "10:15 - 12:00",
      location: "Amfiteatar 4",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A16"],
      time: "10:15 - 12:00",
      location: "13",
    },
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A3"],
      time: "12:15 - 14:00",
      location: "Čitaonica",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A14", "A16"],
      time: "12:15 - 14:00",
      location: "21",
    },
    {
      subject: "Menadžment",
      type: "P",
      groups: ["A4", "A5", "A6"],
      time: "12:15 - 14:00",
      location: "Amfiteatar 4",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A14", "A16"],
      time: "12:15 - 14:00",
      location: "40",
    },
    {
      subject: "Matematika 1",
      type: "P",
      groups: ["A11", "A12", "A13"],
      time: "12:15 - 14:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A2"],
      time: "12:15 - 14:00",
      location: "14",
    },
    {
      subject: "Ekonomija",
      type: "V",
      groups: ["A8", "A9"],
      time: "12:15 - 14:00",
      location: "Amfiteatar 5",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A14", "A16"],
      time: "12:15 - 14:00",
      location: "50",
    },
    {
      subject: "Ekonomija",
      type: "V",
      groups: ["A6", "A16"],
      time: "14:15 - 16:00",
      location: "Amfiteatar 4",
    },
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A9"],
      time: "14:15 - 16:00",
      location: "21",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A10"],
      time: "14:15 - 16:00",
      location: "60",
    },
    {
      subject: "Ekonomija",
      type: "P",
      groups: ["A11", "A12", "A13"],
      time: "14:15 - 16:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Osnovi organizacije",
      type: "P",
      groups: ["A17", "A18"],
      time: "14:15 - 16:00",
      location: "Amfiteatar 5",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A10"],
      time: "14:15 - 16:00",
      location: "61",
    },
    {
      subject: "Ekonomija",
      type: "P",
      groups: ["A10", "A17", "A18"],
      time: "16:15 - 18:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A6"],
      time: "16:15 - 18:00",
      location: "12",
    },
  ],
  Četvrtak: [
    {
      subject: "Engleski jezik u informatici",
      type: "V",
      groups: ["A2"],
      time: "08:15 - 10:00",
      location: "14",
    },
    {
      subject: "Engleski jezik u informatici",
      type: "P",
      groups: ["A7", "A8", "A9", "A10"],
      time: "08:15 - 10:00",
      location: "Amfiteatar 4",
    },
    {
      subject: "Ekonomija",
      type: "V",
      groups: ["A15"],
      time: "08:15 - 10:00",
      location: "20",
    },
    {
      subject: "Osnovi organizacije",
      type: "V",
      groups: ["A16"],
      time: "08:15 - 10:00",
      location: "21",
    },
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A16"],
      time: "10:15 - 12:00",
      location: "21",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A3"],
      time: "10:15 - 12:00",
      location: "13",
    },
    {
      subject: "Ekonomija",
      type: "V",
      groups: ["A2"],
      time: "10:15 - 12:00",
      location: "14",
    },
    {
      subject: "Engleski jezik u informatici",
      type: "P",
      groups: ["A4", "A5", "A6"],
      time: "10:15 - 12:00",
      location: "Amfiteatar 5",
    },
    {
      subject: "Osnovi organizacije",
      type: "V",
      groups: ["A15"],
      time: "10:15 - 12:00",
      location: "20",
    },
    {
      subject: "Engleski jezik u informatici",
      type: "V",
      groups: ["A10"],
      time: "10:15 - 12:00",
      location: "16",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "P",
      groups: ["A7", "A8", "A9"],
      time: "10:15 - 12:00",
      location: "Amfiteatar 4",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A9"],
      time: "12:15 - 14:00",
      location: "60",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A2", "A7"],
      time: "12:15 - 14:00",
      location: "18",
    },
    {
      subject: "Osnovi organizacije",
      type: "V",
      groups: ["A14"],
      time: "12:15 - 14:00",
      location: "17",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A9"],
      time: "12:15 - 14:00",
      location: "61",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A2", "A7"],
      time: "12:15 - 14:00",
      location: "06",
    },
    {
      subject: "Ekonomija",
      type: "V",
      groups: ["A1"],
      time: "12:15 - 14:00",
      location: "30",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A2", "A7"],
      time: "12:15 - 14:00",
      location: "07",
    },
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A15"],
      time: "12:15 - 14:00",
      location: "21",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "P",
      groups: ["A4", "A5", "A6"],
      time: "12:15 - 14:00",
      location: "Amfiteatar 5",
    },
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A18"],
      time: "12:15 - 14:00",
      location: "14",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A11"],
      time: "12:15 - 14:00",
      location: "12",
    },
    {
      subject: "Engleski jezik u informatici",
      type: "V",
      groups: ["A3"],
      time: "12:15 - 14:00",
      location: "13",
    },
    {
      subject: "Ekonomija",
      type: "V",
      groups: ["A3", "A11"],
      time: "14:15 - 16:00",
      location: "Amfiteatar 4",
    },
    {
      subject: "Engleski jezik u informatici",
      type: "V",
      groups: ["A6"],
      time: "14:15 - 16:00",
      location: "12",
    },
    {
      subject: "Engleski jezik u informatici",
      type: "V",
      groups: ["A1"],
      time: "14:15 - 16:00",
      location: "30",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A5", "A18"],
      time: "14:15 - 16:00",
      location: "07",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A5", "A18"],
      time: "14:15 - 16:00",
      location: "18",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A5", "A18"],
      time: "14:15 - 16:00",
      location: "06",
    },
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A14"],
      time: "14:15 - 16:00",
      location: "21",
    },
    {
      subject: "Osnovi organizacije",
      type: "V",
      groups: ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10"],
      time: "16:15 - 18:00",
      location: "21",
    },
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A1"],
      time: "16:15 - 18:00",
      location: "30",
    },
    {
      subject: "Ekonomija",
      type: "V",
      groups: ["A14"],
      time: "16:15 - 18:00",
      location: "20",
    },
  ],
  Petak: [
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A1"],
      time: "08:15 - 10:00",
      location: "61",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A1"],
      time: "08:15 - 10:00",
      location: "60",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A12"],
      time: "08:15 - 10:00",
      location: "14",
    },
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A2"],
      time: "10:15 - 12:00",
      location: "30",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A1"],
      time: "10:15 - 12:00",
      location: "14",
    },
    {
      subject: "Ekonomija",
      type: "V",
      groups: ["A12", "A13"],
      time: "10:15 - 12:00",
      location: "Amfiteatar 4",
    },
    {
      subject: "Engleski jezik u informatici",
      type: "V",
      groups: ["A9"],
      time: "12:15 - 14:00",
      location: "21",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A2"],
      time: "12:15 - 14:00",
      location: "61",
    },
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A7"],
      time: "12:15 - 14:00",
      location: "30",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A4", "A6"],
      time: "12:15 - 14:00",
      location: "06",
    },
    {
      subject: "Ekonomija",
      type: "V",
      groups: ["A10", "A17"],
      time: "12:15 - 14:00",
      location: "Amfiteatar 4",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A4", "A6"],
      time: "12:15 - 14:00",
      location: "07",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A2"],
      time: "12:15 - 14:00",
      location: "60",
    },
    {
      subject: "Engleski jezik u informatici",
      type: "V",
      groups: ["A8"],
      time: "12:15 - 14:00",
      location: "17",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A4", "A6"],
      time: "12:15 - 14:00",
      location: "Čitaonica",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A13"],
      time: "12:15 - 14:00",
      location: "16",
    },
    {
      subject: "Ekonomija",
      type: "V",
      groups: ["A18"],
      time: "14:15 - 16:00",
      location: "15",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A8", "A9"],
      time: "14:15 - 16:00",
      location: "Čitaonica",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A6"],
      time: "14:15 - 16:00",
      location: "61",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A8", "A9"],
      time: "14:15 - 16:00",
      location: "07",
    },
    {
      subject: "Matematika 1",
      type: "V",
      groups: ["A10"],
      time: "14:15 - 16:00",
      location: "16",
    },
    {
      subject: "Osnovi organizacije",
      type: "V",
      groups: ["A17"],
      time: "14:15 - 16:00",
      location: "14",
    },
    {
      subject: "Osnove informaciono komunikacionih tehnologija",
      type: "V",
      groups: ["A8", "A9"],
      time: "14:15 - 16:00",
      location: "06",
    },
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A5"],
      time: "14:15 - 16:00",
      location: "21",
    },
    {
      subject: "Engleski jezik u informatici",
      type: "V",
      groups: ["A4"],
      time: "14:15 - 16:00",
      location: "17",
    },
    {
      subject: "Engleski jezik u informatici",
      type: "V",
      groups: ["A7"],
      time: "14:15 - 16:00",
      location: "30",
    },
    {
      subject: "Elektronsko poslovanje (NA)",
      type: "V",
      groups: ["A6"],
      time: "14:15 - 16:00",
      location: "60",
    },
    {
      subject: "Osnovi organizacije",
      type: "V",
      groups: ["A18"],
      time: "16:15 - 18:00",
      location: "15",
    },
    {
      subject: "Engleski jezik u informatici",
      type: "V",
      groups: ["A5"],
      time: "16:15 - 18:00",
      location: "21",
    },
    {
      subject: "Menadžment",
      type: "V",
      groups: ["A8"],
      time: "16:15 - 18:00",
      location: "Čitaonica",
    },
  ],
};
