import { CurriculumDay } from "./curriculum-day";
import { Day } from "./day";

export const curriculumLastUpdate = new Date("2025-03-22");

type GlobalCurriculum = {
  [Key in Day]: CurriculumDay;
};

export const globalCurriculum: GlobalCurriculum = {
  Ponedeljak: [
    {
      subject: "Inženjering procesa",
      type: "P",
      groups: ["A5", "A6", "A7"],
      time: "08:15-10:00",
      location: "Amfiteatar 4",
    },
    {
      subject: "Psihologija",
      type: "V",
      groups: ["A15", "A16"],
      time: "08:15-10:00",
      location: "Amfiteatar 5",
    },
    {
      subject: "Sociologija",
      type: "V",
      groups: ["A11", "A12", "A13"],
      time: "08:15-10:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Engleski jezik u menadžmentu 1",
      type: "P",
      groups: ["A15", "A16", "A17", "A18"],
      time: "10:15-12:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Psihologija",
      type: "P",
      groups: ["A1", "A2", "A3", "A4"],
      time: "10:15-12:00",
      location: "Amfiteatar 1",
    },
    {
      subject: "Psihologija",
      type: "V",
      groups: ["A5"],
      time: "10:15-12:00",
      location: "13",
    },
    {
      subject: "Psihologija",
      type: "V",
      groups: ["A6"],
      time: "10:15-12:00",
      location: "14",
    },
    {
      subject: "Sociologija",
      type: "V",
      groups: [
        "A1",
        "A2",
        "A3",
        "A4",
        "A5",
        "A6",
        "A7",
        "A8",
        "A9",
        "A10",
        "A14",
      ],
      time: "10:15-12:00",
      location: "Čitaonica",
    },
    {
      subject: "Sociologija",
      type: "V",
      groups: ["A15"],
      time: "12:15-14:00",
      location: "21",
    },
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A2"],
      time: "12:15-14:00",
      location: "13",
    },
    {
      subject: "Engleski jezik u menadžmentu 1",
      type: "V",
      groups: ["A16"],
      time: "12:15-14:00",
      location: "17",
    },
    {
      subject: "Psihologija",
      type: "V",
      groups: ["A13", "A14"],
      time: "12:15-14:00",
      location: "Čitaonica",
    },
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A1"],
      time: "12:15-14:00",
      location: "15",
    },
    {
      subject: "Engleski jezik u menadžmentu 1",
      type: "V",
      groups: ["A18"],
      time: "12:15-14:00",
      location: "18",
    },
    {
      subject: "Psihologija",
      type: "P",
      groups: ["A5", "A6", "A7"],
      time: "12:15-14:00",
      location: "Amfiteatar 1",
    },
    {
      subject: "Psihologija",
      type: "V",
      groups: ["A3", "A4", "A10"],
      time: "12:15-14:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A6"],
      time: "14:15-16:00",
      location: "15",
    },
    {
      subject: "Sociologija",
      type: "V",
      groups: ["A16"],
      time: "14:15-16:00",
      location: "17",
    },
    {
      subject: "Sociologija",
      type: "P",
      groups: ["A11", "A12", "A13", "A14"],
      time: "14:15-16:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A7"],
      time: "14:15-16:00",
      location: "13",
    },
    {
      subject: "Psihologija",
      type: "P",
      groups: ["A8", "A9", "A10"],
      time: "14:15-16:00",
      location: "Amfiteatar 1",
    },
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A5"],
      time: "14:15-16:00",
      location: "16",
    },
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A8"],
      time: "16:15-18:00",
      location: "15",
    },
    {
      subject: "Psihologija",
      type: "V",
      groups: ["A7"],
      time: "16:15-18:00",
      location: "13",
    },
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A9"],
      time: "16:15-18:00",
      location: "16",
    },
    {
      subject: "Psihologija",
      type: "P",
      groups: ["A11", "A12", "A13", "A14"],
      time: "18:15-20:00",
      location: "Amfiteatar 4",
    },
    {
      subject: "Psihologija",
      type: "V",
      groups: ["A1", "A2"],
      time: "18:15-20:00",
      location: "Amfiteatar 3",
    },
  ],
  Utorak: [
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A14"],
      time: "08:15-10:00",
      location: "17",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A1"],
      time: "08:15-10:00",
      location: "20",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A2"],
      time: "08:15-10:00",
      location: "21",
    },
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A13"],
      time: "08:15-10:00",
      location: "16",
    },
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A11"],
      time: "10:15-12:00",
      location: "13",
    },
    {
      subject: "Inženjering procesa",
      type: "V",
      groups: ["A6"],
      time: "10:15-12:00",
      location: "21",
    },
    {
      subject: "Inženjering procesa",
      type: "V",
      groups: ["A5"],
      time: "10:15-12:00",
      location: "20",
    },
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A12"],
      time: "10:15-12:00",
      location: "14",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A14"],
      time: "10:15-12:00",
      location: "17",
    },
    {
      subject: "Matematika 2",
      type: "P",
      groups: ["A1", "A2", "A3", "A4"],
      time: "10:15-12:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A13"],
      time: "10:15-12:00",
      location: "16",
    },
    {
      subject: "Inženjering procesa",
      type: "V",
      groups: ["A7"],
      time: "10:15-12:00",
      location: "30",
    },
    {
      subject: "Matematika 2",
      type: "P",
      groups: ["A11", "A12", "A13", "A14"],
      time: "12:15-14:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A3"],
      time: "12:15-14:00",
      location: "14",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "P",
      groups: ["A5", "A6", "A7"],
      time: "12:15-14:00",
      location: "Amfiteatar 1",
    },
    {
      subject: "Psihologija",
      type: "V",
      groups: ["A9"],
      time: "12:15-14:00",
      location: "30",
    },
    {
      subject: "Psihologija",
      type: "V",
      groups: ["A8"],
      time: "12:15-14:00",
      location: "21",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A4"],
      time: "12:15-14:00",
      location: "15",
    },
    {
      subject: "Matematika 2",
      type: "P",
      groups: ["A5", "A6", "A7"],
      time: "14:15-16:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "P",
      groups: ["A11", "A12", "A13", "A14"],
      time: "14:15-16:00",
      location: "Amfiteatar 1",
    },
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A10"],
      time: "16:15-18:00",
      location: "15",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A12"],
      time: "16:15-18:00",
      location: "17",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A11"],
      time: "16:15-18:00",
      location: "16",
    },
    {
      subject: "Inženjering procesa",
      type: "P",
      groups: ["A1", "A2", "A3", "A4"],
      time: "16:15-18:00",
      location: "Amfiteatar 4",
    },
    {
      subject: "Inženjering procesa",
      type: "V",
      groups: ["A3"],
      time: "18:15-20:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Inženjering procesa",
      type: "V",
      groups: ["A1", "A2"],
      time: "18:15-20:00",
      location: "Amfiteatar 4",
    },
    {
      subject: "Inženjering procesa",
      type: "V",
      groups: ["A4"],
      time: "18:15-20:00",
      location: "Amfiteatar 5",
    },
    {
      subject: "Inženjering procesa",
      type: "P",
      groups: ["A8", "A9", "A10"],
      time: "18:15-20:00",
      location: "Amfiteatar 1",
    },
  ],
  Sreda: [
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A3"],
      time: "08:15-10:00",
      location: "17",
    },
    {
      subject: "Principi programiranja",
      type: "V",
      groups: ["A9"],
      time: "08:15-10:00",
      location: "60 / 62",
    },
    {
      subject: "Psihologija",
      type: "P",
      groups: ["A15", "A16", "A17", "A18"],
      time: "08:15-10:00",
      location: "Amfiteatar 2",
    },
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A4"],
      time: "08:15-10:00",
      location: "18",
    },
    {
      subject: "Principi programiranja",
      type: "P",
      groups: ["A5", "A6", "A7"],
      time: "08:15-10:00",
      location: "Amfiteatar 4",
    },
    {
      subject: "Sociologija",
      type: "P",
      groups: [
        "A1",
        "A2",
        "A3",
        "A4",
        "A5",
        "A6",
        "A7",
        "A8",
        "A9",
        "A10",
        "A15",
        "A16",
        "A17",
        "A18",
      ],
      time: "10:15-12:00",
      location: "Amfiteatar 1",
    },
    {
      subject: "Principi programiranja",
      type: "V",
      groups: ["A8"],
      time: "10:15-12:00",
      location: "60 / 62",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A5"],
      time: "10:15-12:00",
      location: "13",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A6"],
      time: "10:15-12:00",
      location: "14",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A7"],
      time: "10:15-12:00",
      location: "15",
    },
    {
      subject: "Principi programiranja",
      type: "V",
      groups: ["A7"],
      time: "12:15-14:00",
      location: "50 / 40",
    },
    {
      subject: "Principi programiranja",
      type: "P",
      groups: ["A8", "A9", "A10"],
      time: "12:15-14:00",
      location: "Amfiteatar 2",
    },
    {
      subject: "Sociologija",
      type: "V",
      groups: ["A17", "A18"],
      time: "12:15-14:00",
      location: "Čitaonica",
    },
    {
      subject: "Engleski jezik u menadžmentu 1",
      type: "V",
      groups: ["A15"],
      time: "12:15-14:00",
      location: "15",
    },
    {
      subject: "Inženjering procesa",
      type: "V",
      groups: ["A8"],
      time: "14:15-16:00",
      location: "13",
    },
    {
      subject: "Principi programiranja",
      type: "V",
      groups: ["A6"],
      time: "14:15-16:00",
      location: "60 / 61",
    },
    {
      subject: "Principi programiranja",
      type: "V",
      groups: ["A5"],
      time: "14:15-16:00",
      location: "11 / 62",
    },
    {
      subject: "Inženjering procesa",
      type: "V",
      groups: ["A9"],
      time: "14:15-16:00",
      location: "15",
    },
    {
      subject: "Inženjering procesa",
      type: "V",
      groups: ["A10"],
      time: "14:15-16:00",
      location: "14",
    },
    {
      subject: "Psihologija",
      type: "V",
      groups: ["A17"],
      time: "14:15-16:00",
      location: "20",
    },
    {
      subject: "Psihologija",
      type: "V",
      groups: ["A18"],
      time: "14:15-16:00",
      location: "30",
    },
    {
      subject: "Principi programiranja",
      type: "V",
      groups: ["A10"],
      time: "16:15-18:00",
      location: "60 / 61",
    },
    {
      subject: "Engleski jezik u menadžmentu 1",
      type: "V",
      groups: ["A17"],
      time: "16:15-18:00",
      location: "15",
    },
    {
      subject: "Osnove operacionog menadžmenta",
      type: "P",
      groups: ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10"],
      time: "16:15-18:00",
      location: "Amfiteatar 4",
    },
  ],
  Četvrtak: [
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A15"],
      time: "08:15-10:00",
      location: "15",
    },
    {
      subject: "Principi programiranja",
      type: "V",
      groups: ["A1"],
      time: "08:15-10:00",
      location: "50 / 40",
    },
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A16"],
      time: "08:15-10:00",
      location: "14",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A18"],
      time: "08:15-10:00",
      location: "17",
    },
    {
      subject: "Principi programiranja",
      type: "V",
      groups: ["A2"],
      time: "08:15-10:00",
      location: "61 / 60",
    },
    {
      subject: "Matematika 2",
      type: "P",
      groups: ["A8", "A9", "A10"],
      time: "08:15-10:00",
      location: "Amfiteatar 2",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A17"],
      time: "08:15-10:00",
      location: "16",
    },
    {
      subject: "Principi programiranja",
      type: "V",
      groups: ["A4"],
      time: "08:15-10:00",
      location: "62",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A10"],
      time: "10:15-12:00",
      location: "15",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A9"],
      time: "10:15-12:00",
      location: "14",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A8"],
      time: "10:15-12:00",
      location: "13",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "P",
      groups: ["A1", "A2", "A3", "A4"],
      time: "10:15-12:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Matematika 2",
      type: "P",
      groups: ["A15", "A16", "A17", "A18"],
      time: "10:15-12:00",
      location: "Amfiteatar 2",
    },
    {
      subject: "Principi programiranja",
      type: "P",
      groups: ["A1", "A2", "A3", "A4"],
      time: "12:15-14:00",
      location: "Amfiteatar 4",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "P",
      groups: ["A8", "A9", "A10"],
      time: "12:15-14:00",
      location: "Amfiteatar 1",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A15"],
      time: "12:15-14:00",
      location: "16",
    },
    {
      subject: "Engleski jezik u menadžmentu 1",
      type: "P",
      groups: ["A11", "A12", "A13", "A14"],
      time: "12:15-14:00",
      location: "Amfiteatar 5",
    },
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A17"],
      time: "12:15-14:00",
      location: "15",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "V",
      groups: ["A16"],
      time: "12:15-14:00",
      location: "17",
    },
    {
      subject: "Matematika 2",
      type: "V",
      groups: ["A18"],
      time: "12:15-14:00",
      location: "14",
    },
    {
      subject: "Francuski jezik u informatici",
      type: "P",
      groups: ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10"],
      time: "14:15-16:00",
      location: "12",
    },
    {
      subject: "Engleski jezik u menadžmentu 1",
      type: "V",
      groups: ["A14"],
      time: "14:15-16:00",
      location: "21",
    },
    {
      subject: "Psihologija",
      type: "V",
      groups: ["A12"],
      time: "14:15-16:00",
      location: "13",
    },
    {
      subject: "Osnove operacionog menadžmenta",
      type: "V",
      groups: ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10"],
      time: "14:15-16:00",
      location: "Amfiteatar 5",
    },
    {
      subject: "Menadžment tehnologije i razvoja",
      type: "P",
      groups: ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10"],
      time: "14:15-16:00",
      location: "Amfiteatar 2",
    },
    {
      subject: "Engleski jezik u menadžmentu 1",
      type: "V",
      groups: ["A13"],
      time: "14:15-16:00",
      location: "18",
    },
    {
      subject: "Psihologija",
      type: "V",
      groups: ["A11"],
      time: "14:15-16:00",
      location: "Amfiteatar 3",
    },
    {
      subject: "Uvod u informacione sisteme",
      type: "P",
      groups: ["A15", "A16", "A17", "A18"],
      time: "14:15-16:00",
      location: "Amfiteatar 1",
    },
    {
      subject: "Francuski jezik u informatici",
      type: "V",
      groups: ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10"],
      time: "16:15-18:00",
      location: "12",
    },
    {
      subject: "Engleski jezik u menadžmentu 1",
      type: "V",
      groups: ["A12"],
      time: "16:15-18:00",
      location: "21",
    },
    {
      subject: "Engleski jezik u menadžmentu 1",
      type: "V",
      groups: ["A11"],
      time: "16:15-18:00",
      location: "18",
    },
    {
      subject: "Menadžment tehnologije i razvoja",
      type: "V",
      groups: ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10"],
      time: "16:15-18:00",
      location: "Amfiteatar 2",
    },
    {
      subject: "Principi programiranja",
      type: "V",
      groups: ["A3"],
      time: "18:15-20:00",
      location: "62 / 50",
    },
  ],
  Petak: [],
};
